export const FIND_BY_SEARCH = 'FIND_REPOSITORIES';
export const FIND_BY_SEARCH_PER_PAGE = 'FIND_BY_SEARCH_PER_PAGE';

export const GET_REPOS_START = 'GET/REPOSITORIES/START';
export const GET_REPOS_FAILURE = 'GET/REPOSITORIES/FAILURE';
export const GET_REPOS_SUCCESS = 'GET/REPOSITORIES/SUCCESS';

export const GET_REPOS_PER_PAGE = 'GET/REPOSITORIES_PER_PAGE';
export const CLEAR_FILTER = 'CLEAR/FILTER';

export const SET_QUERY_TITLE = 'SET/QUERY_TITLE';

export const SET_FILTER_BY_STARS = 'SET/FILTERS/STARS';
export const SET_FILTER_BY_FORKS = 'SET/FILTERS/FORKS';

export const SET_PER_PAGE = 'SET/PAGE/ADD';
export const LOGIN = 'AUTH/LOGIN';

export const GET_USER_DATA_START = 'GET_USER_DATA_START';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
